sudo: required

language: java

install:
  - jdk_switcher use oraclejdk8
  - ./mvnw clean install --quiet jacoco:report coveralls:report
  - ./mvnw clean javadoc:javadoc -Dmaven.test.skip=true --quiet

